# name: Simply Grey
# markdown: redcarpet
# highlighter: pygments
# github: https://www.github.com/liamsymonds
# about: I am an independent developer from the sunny UK. I dabble in Ruby, play in C and I'm an avid systems administrator.
# urls:
#     - text: github
#       url: https://github.com/liamsymonds
# baseurl: '/simplygrey-jekyll'

# Site settings
name: Pooja Sethi
email: sethi.pooja@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Pooja Sethi's blog on computer science, technology, and figuring out life.
baseurl: "" # the subpath of your site, e.g. /blog
highlighter: pygments
urls: "http://yourdomain.com" # the base hostname & protocol for your site
paginate: 1
paginate_path: "/blog/page:num/"
plugins: [jekyll-paginate]

# Social media accounts
twitter: pjasethi
github: poojasethi
linkedin: sethipooja
facebook: pjasethi
instagram: poojasethi17
medium: pjasethi

# Build settings
markdown: kramdown
